# Generated by Django 4.2.7 on 2023-12-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(null=True)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
