# Generated by Django 4.2.7 on 2023-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
