# Generated by Django 4.2.7 on 2024-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_department_employees_position_delete_employeemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='status',
            new_name='posi_status',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='code',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='position',
            name='posi_description',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='posi_name',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='middlename',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
